discovery-search-widgets: Added SearchInput in MainNavigation
jeanfrancoislarente/Sitecore.Demo.XmCloud.PlaySummit pull request #4
Opened 2022-10-26 19:19 UTC by InakiAbete-Reflektion

…ts elements

2022-10-26 20:14 UTC, jflheureux requested changes

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/src/components/PreviewSearchContent/NewsCard.tsx
> +          <Text tag="div" className={`item-title`} field={{ value: name }} />
The Sitecore JSS `Text` component is not needed to render the `name` prop. This component is not rendered by Sitecore JSS. This should be enough:
`<div className="item-title">{name}</div>`

Please remove the use of the Sitecore JSS fields in new code for all the files.

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/src/components/PreviewSearchContent/NewsCard.tsx
> +      <a className={`grid-item news-item`}>
Why are the class names in template strings:
```
className={`grid-item news-item`}
```

instead of regular strings: `className="grid-item news-item"` ?

Is there a benefit to that?

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/src/components/PreviewSearchContent/NewsCard.tsx
> +        <img className={`news-image`} src={image_url} alt={`News image`} height="100" width="100" />
Why is the alt text in a template string:
```
alt={`News image`}
```

instead of a regular string: `alt="News image"` ?

Is there a benefit to that?

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/src/components/PreviewSearchContent/PreviewSearchNewsList.tsx
> +            // eslint-disable-next-line react/jsx-key
key validations should not be ignored. Is there a way to define a key for these components?

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/src/components/PreviewSearchContent/SuggestionList.tsx
> +          list.map((item, index) => <Suggestion key={index} {...item}></Suggestion>)}
Using the index as a key is a code smell that can lead to UI update problems in React. The key should be unique to the thing rendered so this thing can move position in the list and keep its key.

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/src/lib/next-config/plugins/transpileModules.js
> +// DEMO TEAM CUSTOMIZATION (whole file) - Add Next bundle analyzer
The comment does not match the file content

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/src/components/Search/connect.tsx
> +// import { useQuery } from '@tanstack/react-query';
This file is only commented out code. Can it be deleted?

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/src/components/Search/Search.tsx
> +              <div className="search-main-container">{props.children}</div>
I am feeling that defining the header/footer and all the other page content in this component does net feel right. This should be defined at the search page level, not the component level.

That being said, I do not see a search page added to this project. Is it missing?

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/.env
> +NEXT_PUBLIC_DISCOVER_API_DOMAIN=229001437
Those new environment variables should be named with SEARCH instead of DISCOVER.

We should not commit the environment variables values. Just their name and an equal sign.

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/.env
> +# to enable full ISR (Incremental Static Regeneration) flow
Please revert removal of whitespaces on line ends. These are left there to facilitate upgrades when comparing the files with new starter kit versions.

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/package.json
> +{
Please revert line end format change. On some files like this one, it seems all line ends were changed.

2022-10-26 20:14 UTC, jflheureux commented on src/rendering/src/Layout.tsx
> +  Field,
Please revert imports order changes. The import order is important to us to facilitate upgrades when comparing the files with new starter kit versions.

2022-10-26 20:23 UTC, FedericoRossi-Reflektion commented on src/rendering/src/components/PreviewSearchContent/NewsCard.tsx
> +          <Text tag="div" className={`item-title`} field={{ value: name }} />
Sure, will do 👍

2022-10-26 20:24 UTC, InakiAbete-Reflektion commented on src/rendering/.env
> +NEXT_PUBLIC_DISCOVER_API_DOMAIN=229001437
OK.

Yes, they were hardcoded for the demo because we didn't have access to Vercel in order to deploy the app and enable the feature 👍

2022-10-26 20:24 UTC, FedericoRossi-Reflektion commented on src/rendering/src/components/PreviewSearchContent/NewsCard.tsx
> +      <a className={`grid-item news-item`}>
I will update it to regular strings

2022-10-26 20:24 UTC, FedericoRossi-Reflektion commented on src/rendering/src/components/PreviewSearchContent/NewsCard.tsx
> +        <img className={`news-image`} src={image_url} alt={`News image`} height="100" width="100" />
Same, I will update it to regular string

2022-10-26 20:47 UTC, FedericoRossi-Reflektion commented on src/rendering/src/components/PreviewSearchContent/PreviewSearchNewsList.tsx
> +            // eslint-disable-next-line react/jsx-key
Yes, list's elements have id. So I will use it.

2022-10-27 18:08 UTC, jflheureux commented on src/rendering/src/assets/css/main.css
> +@charset "UTF-8";
Could this file line endings please be fixed so GitHub only see modified lines as changed? Thanks

2022-11-03 19:30 UTC, jflheureux commented
Replaced by https://github.com/Sitecore/Sitecore.Demo.XmCloud.PlaySummit/pull/42

2022-11-03 19:30 UTC, closed without merging